name: 🏃‍♂Bun

on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

env:
  LANG: ja_JP.UTF-8
  RUBY_YJIT_ENABLE: 1
  TZ: Asia/Tokyo

# $ npx @pkgdeps/update-github-actions-permissions ".github/workflows/*.{yaml,yml}"
permissions:
  contents: read

jobs:
  bun_install:
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    steps:
      - name: $ git clone する
        # https://github.com/actions/checkout/releases
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: bun のセットアップを行う
        # https://github.com/oven-sh/setup-bun/releases
        uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # v2.2.0
        # with:
        #   bun-version: 1.2.8 # or "latest", "canary", <sha>
      - name: Node.js のセットアップを行う
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version-file: '.node-version'
      - name: package.json の依存関係をインストールする ($ bun install)
        run: bun install --frozen-lockfile
