name: PostgreSQL

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
  workflow_dispatch:

env:
  TZ: Asia/Tokyo

permissions: write-all

jobs:
  postgresql:
    name: PostgreSQL を ubuntu-24.04 のイメージのみで実行する
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    steps:
      - name: コードをチェックアウトする
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: （デバッグ用）PostgreSQL が起動していることを確認する
        run: |
          # sudo systemctl status postgresql.service
          sudo service postgresql status || true
      # https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2404-Readme.md#postgresql
      - name: PostgreSQL を有効にする
        run: |
          # sudo systemctl start postgresql.service
          sudo service postgresql start
      - name: （デバッグ用）PostgreSQL が起動していることを確認する
        run: |
          # sudo systemctl status postgresql.service
          sudo service postgresql status
      - name: （デバッグ用）PostgreSQL クライアント のバージョンを確認する
        run: |
          psql --version
      - name: psql コマンドを実行する
        # 前述ドキュメントのとおり、デフォルトユーザ名は postgres である
        run: |
          sudo -u postgres psql -c 'SELECT version();'
      - name: users テーブル を作成する（カラムは id, name）
        run: |
          sudo -u postgres psql -c 'CREATE TABLE users (id SERIAL PRIMARY KEY, name VARCHAR(255));'
      - name: users テーブル に仮のデータを 2つ 投入する
        run: |
          sudo -u postgres psql -c "INSERT INTO users (name) VALUES ('Alice');"
          sudo -u postgres psql -c "INSERT INTO users (name) VALUES ('Bob');"
      - name: users テーブル のデータを確認する
        run: |
          sudo -u postgres psql -c 'SELECT * FROM users;'
